<?php
    $_code = $this->getMethodCode();
    $_accounts = \Magento\Framework\App\ObjectManager::getInstance()->get('EPG\EasyPaymentGateway\Helper\Data')->getAccounts();
    $isSSL = (\Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface')->getStore()->isFrontUrlSecure() && \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\RequestInterface')->isSecure());
    $removeAccountUrl =  Mage::getUrl('easypaymentgateway/payment/removeAccount', ['_secure' => $isSSL]);
?>

<div class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

    <div class="epg-form">
        <?php
            // Test mode or store has ssl cert
            if ($_isSSL) {
        ?>

            <div class="logos">
                <?php
                    $logos = null;
                    if (!empty($_allowedCards)) {
                        echo '<span class="label">'. __('Pay with') . '&nbsp;</span>';
                        $logos = explode(',', $_allowedCards);
                    }

                    if (!empty($logos) && in_array('visa', $logos)) {
                        echo '<span class="epg-logo"><img src="' . $_baseSkinUrl . 'visa.png" /></span>';
                    }
                    if (!empty($logos) && in_array('master_card', $logos)) {
                        echo '<span class="epg-logo"><img src="' . $_baseSkinUrl . 'master_card.png" /></span>';
                    }
                    if (!empty($logos) && in_array('maestro', $logos)) {
                        echo '<span class="epg-logo"><img src="' . $_baseSkinUrl . 'maestro.png" /></span>';
                    }
                    if (!empty($logos) && in_array('american_express', $logos)) {
                        echo '<span class="epg-logo"><img src="' . $_baseSkinUrl . 'american_express.png" /></span>';
                    }
                ?>
            </div>

            <div class="block-form" data-disable-account-url="<?php echo $removeAccountUrl?>" data-confirm-disable-account="<?php echo __('Do you want disable this payment account?')?>" id="payment-form" style="padding: 20px 0;">

                 <?php if (!empty($_accounts)){ ?>
                     <div class="accounts-header"><?php echo __('Please, select a credit or debit card') ?></div>
                     <ul class="accounts">
                        <?php
                            foreach($_accounts as $key => $account) {
                        ?>
                            <li>
                                <input id="account<?php echo $account['accountId']?>" type="radio" name="payment[account]" value="<?php echo $account['accountId'] ?>" <?php if ($key == 0){ ?>checked<?php } ?>/>
                                <label for="account<?php echo $account['accountId']?>" class="account" data-account-id="<?php echo $account['accountId']?>">
                                    <?php
                                        $accountInfo=[];
                                        foreach ($account['values'] as $value) {
                                            $accountInfo[$value['name']] = $value['value'];
                                        }
                                    ?>

                                    <span class="card-type">
                                        <strong><?php echo __('Card type')?></strong> <?php echo $accountInfo['cardType']?>
                                    </span>
                                    <span class="card-masked">
                                        <strong><?php echo __('Card number')?></strong> <?php echo $accountInfo['maskedCardNumber']?>
                                    </span>
                                    <span class="disable"></span>
                                </label>
                            </li>
                        <?php } ?>

                        <li>
                            <input id="account0" type="radio" name="payment[account]" value="0" />
                            <label for="account0" class="account new-card" data-account-id="">
                                <span class="card-type">
                                    <strong><?php echo __('New card')?></strong>
                                </span>
                            </label>
                        </li>
                     </ul>
                <?php } ?>

                  <div class="new-account">
                    <div class="row card-holder-name <?php if (!empty($_accounts)){ ?>hidden<?php } ?>">
                        <label for="<?php echo $_code ?>_card_holder_name" class="required"><?php echo __('Card holder name') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Helper\AbstractHelper')->quoteEscape(__('Card holder name')) ?>" class="input-text required-entry" id="<?php echo $_code ?>_card_holder_name" name="payment[card_holder_name]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>" />
                        </div>
                    </div>

                    <div class="row card-number <?php if (!empty($_accounts)){ ?>hidden<?php } ?>">
                        <label for="<?php echo $_code ?>_card_number" class="required"><?php echo __('Credit/Debit card number') ?></label>
                        <div class="input-box">
                            <input type="text" id="<?php echo $_code ?>_card_number" name="payment[card_number]" title="<?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Helper\AbstractHelper')->quoteEscape(__('Credit/Debit card number')) ?>" class="input-text validate-cc-number required-entry" value="" />
                        </div>
                    </div>

                    <div class="row card-cvn">
                        <label for="<?php echo $_code ?>_card_cvn" class="required"><?php echo __('CVN') ?></label>
                        <div class="input-box">
                            <input type="text" id="<?php echo $_code ?>_card_cvn" name="payment[card_cvn]" title="<?php echo \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\App\Helper\AbstractHelper')->quoteEscape(__('CVN')) ?>" class="input-text validate-cvn-number required-entry" value="" />
                        </div>
                    </div>

                    <div class="row card-expiration input-box <?php if (!empty($_accounts)){ ?>hidden<?php } ?>">
                        <label for="<?php echo $_code ?>_expiration" class="required"><?php echo __('Expiration Date (MM/YY)') ?></label>
                        <div class="input-box">
                            <div class="v-fix">
                                <select id="<?php echo $_code ?>_card_expiry_month" name="payment[card_expiry_month]" class="month">
                                <?php $_ccExpMonth = $this->getInfoData('card_expiry_month') ?>
                                <?php foreach ($this->getMonths() as $k=>$v): ?>
                                    <option value="<?php echo $v ?>"<?php if($v==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                                </select>
                            </div>
                            <div class="v-fix">
                                <?php $_ccExpYear = $this->getInfoData('card_expiry_year') ?>
                                <select id="<?php echo $_code ?>_card_expiry_year" name="payment[card_expiry_year]" class="year">
                                <?php foreach ($this->getYears() as $k=>$v): ?>
                                    <option value="<?php echo $v ?>"<?php if($v==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>


            </div>

        <?php
            // If not test mode or store has not ssl cert
            } else {
        ?>
            <div class="alert alert-warning"><?php echo __('Sorry, you can only use this payment gateway through a secure protocol.')?></div>
        <?php
            }
        ?>
    </div>

</div>

<script>
require(["jquery", "prototype"], function(jQuery) {

_EPGInitFunctions();

});
</script>
